"""Demo data: voorraad Kraakman + voorbeeld zoekvragen."""

from datetime import date

INVENTORY = [
    {
        "id": "KR-001",
        "model": "6R 250",
        "year": 2021,
        "hours": 1850,
        "price": 185000,
        "location": "Creil",
        "features": ["CommandPRO", "GPS", "frontloader", "airco", "AutoTrac"],
        "stock_days": 45,
        "condition": "Zeer goed",
        "description": "John Deere 6R 250, volledig uitgerust, dealer onderhouden",
    },
    {
        "id": "KR-002",
        "model": "6155R",
        "year": 2019,
        "hours": 3200,
        "price": 95000,
        "location": "Dronten",
        "features": ["GPS", "airco", "CommandCenter"],
        "stock_days": 120,
        "condition": "Goed",
        "description": "John Deere 6155R, nette staat, GPS ready",
    },
    {
        "id": "KR-003",
        "model": "6195R",
        "year": 2020,
        "hours": 2100,
        "price": 135000,
        "location": "Emmeloord",
        "features": ["CommandPRO", "GPS", "AutoTrac", "airco"],
        "stock_days": 30,
        "condition": "Zeer goed",
        "description": "John Deere 6195R, premium uitvoering met AutoTrac",
    },
    {
        "id": "KR-004",
        "model": "7R 310",
        "year": 2022,
        "hours": 980,
        "price": 245000,
        "location": "Marknesse",
        "features": ["CommandPRO", "GPS", "AutoTrac", "frontloader", "airco", "IVT"],
        "stock_days": 15,
        "condition": "Als nieuw",
        "description": "John Deere 7R 310, bijna nieuw, full options",
    },
    {
        "id": "KR-005",
        "model": "6M 200",
        "year": 2018,
        "hours": 4500,
        "price": 72000,
        "location": "Kraggenburg",
        "features": ["airco", "CommandCenter"],
        "stock_days": 180,
        "condition": "Redelijk",
        "description": "John Deere 6M 200, betrouwbare werkmachine",
    },
    {
        "id": "KR-006",
        "model": "5100E",
        "year": 2023,
        "hours": 320,
        "price": 58000,
        "location": "Nagele",
        "features": ["airco"],
        "stock_days": 60,
        "condition": "Als nieuw",
        "description": "John Deere 5100E, compact en zuinig",
    },
    {
        "id": "KR-007",
        "model": "6R 185",
        "year": 2020,
        "hours": 2800,
        "price": 125000,
        "location": "Rutten",
        "features": ["GPS", "CommandPRO", "airco", "frontloader"],
        "stock_days": 90,
        "condition": "Goed",
        "description": "John Deere 6R 185, veelzijdige allrounder",
    },
    {
        "id": "KR-008",
        "model": "8R 340",
        "year": 2021,
        "hours": 1500,
        "price": 295000,
        "location": "Tollebeek",
        "features": ["CommandPRO", "GPS", "AutoTrac", "IVT", "airco", "frontPTO"],
        "stock_days": 25,
        "condition": "Zeer goed",
        "description": "John Deere 8R 340, topklasse met alle opties",
    },
]

WANTED_ADS = [
    {
        "id": "W-001",
        "source": "boerenbusiness",
        "text": "Gezocht: John Deere 6R 150-185, niet ouder dan 2019, max 3000 uur. Budget 100-140k. Moet GPS en airco hebben. Regio Flevoland.",
        "date": "2025-03-20",
        "contact": "Akkerbouwer uit Zeewolde",
    },
    {
        "id": "W-002",
        "source": "marktplaats",
        "text": "Op zoek naar JD 6155R of 6195R, bouwjaar 2018-2021, max 4000 uur. Budget tot 130k. Liefst met CommandPRO en frontloader.",
        "date": "2025-03-18",
        "contact": "Melkveehouder uit Kampen",
    },
    {
        "id": "W-003",
        "source": "facebook",
        "text": "Wie heeft er een John Deere 6M serie, 180+ pk? Niet ouder dan 2017, max 5000 uur. Budget 60-80k. Airco is een must.",
        "date": "2025-03-22",
        "contact": "Loonwerker uit Urk",
    },
    {
        "id": "W-004",
        "source": "boerenbusiness",
        "text": "Gevraagd: grote JD trekker, 7R of 8R serie, 280-350 pk. Bouwjaar 2020+, max 2000 uur. Budget 200-300k. AutoTrac en IVT gewenst.",
        "date": "2025-03-21",
        "contact": "Groot akkerbouwbedrijf uit Lelystad",
    },
    {
        "id": "W-005",
        "source": "marktplaats",
        "text": "Gezocht: kleine John Deere 5E serie, 75-100 pk. Voor erfwerk en licht transport. Max 1000 uur. Budget tot 65k.",
        "date": "2025-03-19",
        "contact": "Hobbyboer uit Swifterbant",
    },
]
